---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
  namespace: outline
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
spec:
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:14
        name: postgres
        resources: {}
        volumeMounts:
          - name: pgdata
            mountPath: /var/lib/postgres
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: outline-secrets
                key: database-password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: outline-secrets
                key: database-user
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: outline-secrets
                key: database-name
status: {}
